//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ControlNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ControlNames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ControlNames", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Button.
        /// </summary>
        internal static string Control_Button {
            get {
                return ResourceManager.GetString("Control.Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckBox.
        /// </summary>
        internal static string Control_CheckBox {
            get {
                return ResourceManager.GetString("Control.CheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GridView.
        /// </summary>
        internal static string Control_GridView {
            get {
                return ResourceManager.GetString("Control.GridView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HyperLink.
        /// </summary>
        internal static string Control_HyperLink {
            get {
                return ResourceManager.GetString("Control.HyperLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        internal static string Control_Image {
            get {
                return ResourceManager.GetString("Control.Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ImageButton.
        /// </summary>
        internal static string Control_ImageButton {
            get {
                return ResourceManager.GetString("Control.ImageButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label.
        /// </summary>
        internal static string Control_Label {
            get {
                return ResourceManager.GetString("Control.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LinkButton.
        /// </summary>
        internal static string Control_LinkButton {
            get {
                return ResourceManager.GetString("Control.LinkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List.
        /// </summary>
        internal static string Control_List {
            get {
                return ResourceManager.GetString("Control.List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Literal.
        /// </summary>
        internal static string Control_Literal {
            get {
                return ResourceManager.GetString("Control.Literal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Panel.
        /// </summary>
        internal static string Control_Panel {
            get {
                return ResourceManager.GetString("Control.Panel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RadioButton.
        /// </summary>
        internal static string Control_RadioButton {
            get {
                return ResourceManager.GetString("Control.RadioButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TextBox.
        /// </summary>
        internal static string Control_TextBox {
            get {
                return ResourceManager.GetString("Control.TextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to undefined.
        /// </summary>
        internal static string Control_undefined {
            get {
                return ResourceManager.GetString("Control.undefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validator.
        /// </summary>
        internal static string Control_Validator {
            get {
                return ResourceManager.GetString("Control.Validator", resourceCulture);
            }
        }
    }
}
